### ISSUE TITLE
NameError: name 'raw_input' is not defined

### ISSUE THREAD

**Issue by NarutoBetty** [hctech/mysql-schema-sync#2]
运行报错 ：
NameError: name 'raw_input' is not defined
=== end compare mysql db schema ===
Traceback (most recent call last):
  File "sync_mysql_schema.py", line 89, in <module>
    main()
  File "sync_mysql_schema.py", line 58, in main
    is_exec = raw_input("exec sync ddl sql on target db? [Y/N]")
NameError: name 'raw_input' is not defined

**Comment by NarutoBetty** [comment]
python3.0 后raw_input变成了input,修改后可以了，可以价格版本区分，同步成功了
